# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action_request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='action_request.proto',
  package='backend',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x61\x63tion_request.proto\x12\x07\x62\x61\x63kend\"0\n\x07\x43ontext\x12\x11\n\tdevice_id\x18\x01 \x01(\x05\x12\x12\n\nsession_id\x18\x02 \x01(\x05\"e\n\rDeviceDetails\x12\x17\n\x0f\x63\x61pture_formats\x18\x01 \x03(\x05\x12\x16\n\x0e\x64\x65vice_version\x18\x02 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\"\xb3\x06\n\rActionRequest\x12-\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1d.backend.ActionRequest.Action\x12!\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x10.backend.Context\x12\"\n\x13response_successful\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x15\n\rcapture_count\x18\x04 \x01(\x05\x12\x38\n\x0c\x63\x61mera_state\x18\x05 \x01(\x0e\x32\".backend.ActionRequest.CameraState\x12\x15\n\rexposure_time\x18\x06 \x01(\x05\x12\x10\n\x08\x66_number\x18\x07 \x01(\x05\x12\x18\n\x10\x61perture_options\x18\x08 \x03(\x05\x12\x0f\n\x07lens_id\x18\t \x01(\x05\x12\x12\n\niso_number\x18\n \x01(\x05\x12.\n\x0e\x64\x65vice_details\x18\x0c \x01(\x0b\x32\x16.backend.DeviceDetails\"\x90\x03\n\x06\x41\x63tion\x12\x1d\n\x19\x41\x43TION_GET_DEVICE_DETAILS\x10\x01\x12\x18\n\x14\x41\x43TION_CAPTURE_IMAGE\x10\x02\x12%\n!ACTION_MULTIPLE_CAPTURES_BY_COUNT\x10\x03\x12\x1b\n\x17\x41\x43TION_GET_CAMERA_STATE\x10\x04\x12\x1c\n\x18\x41\x43TION_GET_EXPOSURE_TIME\x10\x05\x12\x1c\n\x18\x41\x43TION_SET_EXPOSURE_TIME\x10\x06\x12\x1e\n\x1a\x41\x43TION_SET_APERTURE_F_STOP\x10\x07\x12\x1e\n\x1a\x41\x43TION_GET_APERTURE_F_STOP\x10\x08\x12\x1f\n\x1b\x41\x43TION_GET_APERTURE_OPTIONS\x10\t\x12\x16\n\x12\x41\x43TION_GET_LENS_ID\x10\n\x12\x19\n\x15\x41\x43TION_GET_ISO_NUMBER\x10\x0b\x12\x19\n\x15\x41\x43TION_SET_ISO_NUMBER\x10\x0c\x12\x1e\n\x1a\x41\x43TION_ERROR_RESEND_ACTION\x10\r\"0\n\x0b\x43\x61meraState\x12\x0c\n\x08\x43OMPLETE\x10\x01\x12\x13\n\x0fPENDING_CAPTURE\x10\x02'
)



_ACTIONREQUEST_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='backend.ActionRequest.Action',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION_GET_DEVICE_DETAILS', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_CAPTURE_IMAGE', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_MULTIPLE_CAPTURES_BY_COUNT', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_GET_CAMERA_STATE', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_GET_EXPOSURE_TIME', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_SET_EXPOSURE_TIME', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_SET_APERTURE_F_STOP', index=6, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_GET_APERTURE_F_STOP', index=7, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_GET_APERTURE_OPTIONS', index=8, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_GET_LENS_ID', index=9, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_GET_ISO_NUMBER', index=10, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_SET_ISO_NUMBER', index=11, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTION_ERROR_RESEND_ACTION', index=12, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=556,
  serialized_end=956,
)
_sym_db.RegisterEnumDescriptor(_ACTIONREQUEST_ACTION)

_ACTIONREQUEST_CAMERASTATE = _descriptor.EnumDescriptor(
  name='CameraState',
  full_name='backend.ActionRequest.CameraState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMPLETE', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PENDING_CAPTURE', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=958,
  serialized_end=1006,
)
_sym_db.RegisterEnumDescriptor(_ACTIONREQUEST_CAMERASTATE)


_CONTEXT = _descriptor.Descriptor(
  name='Context',
  full_name='backend.Context',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='backend.Context.device_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='backend.Context.session_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=81,
)


_DEVICEDETAILS = _descriptor.Descriptor(
  name='DeviceDetails',
  full_name='backend.DeviceDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='capture_formats', full_name='backend.DeviceDetails.capture_formats', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_version', full_name='backend.DeviceDetails.device_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='backend.DeviceDetails.manufacturer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='backend.DeviceDetails.model', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=184,
)


_ACTIONREQUEST = _descriptor.Descriptor(
  name='ActionRequest',
  full_name='backend.ActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='backend.ActionRequest.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='context', full_name='backend.ActionRequest.context', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_successful', full_name='backend.ActionRequest.response_successful', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capture_count', full_name='backend.ActionRequest.capture_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_state', full_name='backend.ActionRequest.camera_state', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exposure_time', full_name='backend.ActionRequest.exposure_time', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='f_number', full_name='backend.ActionRequest.f_number', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aperture_options', full_name='backend.ActionRequest.aperture_options', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lens_id', full_name='backend.ActionRequest.lens_id', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iso_number', full_name='backend.ActionRequest.iso_number', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_details', full_name='backend.ActionRequest.device_details', index=10,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTIONREQUEST_ACTION,
    _ACTIONREQUEST_CAMERASTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=1006,
)

_ACTIONREQUEST.fields_by_name['action'].enum_type = _ACTIONREQUEST_ACTION
_ACTIONREQUEST.fields_by_name['context'].message_type = _CONTEXT
_ACTIONREQUEST.fields_by_name['camera_state'].enum_type = _ACTIONREQUEST_CAMERASTATE
_ACTIONREQUEST.fields_by_name['device_details'].message_type = _DEVICEDETAILS
_ACTIONREQUEST_ACTION.containing_type = _ACTIONREQUEST
_ACTIONREQUEST_CAMERASTATE.containing_type = _ACTIONREQUEST
DESCRIPTOR.message_types_by_name['Context'] = _CONTEXT
DESCRIPTOR.message_types_by_name['DeviceDetails'] = _DEVICEDETAILS
DESCRIPTOR.message_types_by_name['ActionRequest'] = _ACTIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Context = _reflection.GeneratedProtocolMessageType('Context', (_message.Message,), {
  'DESCRIPTOR' : _CONTEXT,
  '__module__' : 'action_request_pb2'
  # @@protoc_insertion_point(class_scope:backend.Context)
  })
_sym_db.RegisterMessage(Context)

DeviceDetails = _reflection.GeneratedProtocolMessageType('DeviceDetails', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEDETAILS,
  '__module__' : 'action_request_pb2'
  # @@protoc_insertion_point(class_scope:backend.DeviceDetails)
  })
_sym_db.RegisterMessage(DeviceDetails)

ActionRequest = _reflection.GeneratedProtocolMessageType('ActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONREQUEST,
  '__module__' : 'action_request_pb2'
  # @@protoc_insertion_point(class_scope:backend.ActionRequest)
  })
_sym_db.RegisterMessage(ActionRequest)


# @@protoc_insertion_point(module_scope)
