"""empty message

Revision ID: def95ed674c8
Revises: 22b265014c36
Create Date: 2020-08-12 15:09:58.766389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def95ed674c8'
down_revision = '22b265014c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('image_file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'image_file_name')
    # ### end Alembic commands ###
